### ISSUE TITLE
UCH

### ISSUE THREAD

**Issue by colonetti** [rjmalves/idessem#22]
Oi, pessoal

Parabéns pelos pacotes. Eles são bastante interesantes e muito uteis

Eu tenho uma dúvida, e gostaria da ajuda de vocês, se possível.

Eu notei que vocês adicionaram funcionalidades para o Unit Commitment Hidráulico. Porém, eu não consigo localizar os arquivos de entrada que contém os dados do UCH que alimentam essas funcionalidades implementadas. Esses arquivos serão distribuídos no sintegre? Ou eles só estarão disponíveis para usuários comerciais do DESSEM? Alguma dica de onde eu posso encontrá-los? :)

Atenciosamente,

**Comment by marianasnoel** [comment]
Olá, @colonetti!
Agradeço o interesse nos pacotes!

Conforme manual do DESSEM disponibilizado pelo desenvolvedor CEPEL as funcionalidades para consideração do Unit Commitment Hidráulico estão disponíveis na [versão 19.3.3](https://www.cepel.br/wp-content/uploads/2023/05/DESSEM_ManualUsuario_19.3.3.pdf). Assim, o suporte de leitura e escrita de arquivos de entrada que definem dados para tal funcionalidade foi incorporado na idessem, de forma a possibilitar realização de estudos e testes. Pessoalmente, não tenho nenhuma previsão de quando serão divulgados dados oficiais ou de teste, mas acredito que, quando forem, serão através de canais oficiais como o SINtegre mesmo.

**Comment by colonetti** [comment]
Oi, @marianasnoel 

Tá bem. Obrigado pela explicação.
